# Generated by Django 5.0.3 on 2025-01-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogkind_alter_blog_kind_delete_blogdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='kind',
        ),
    ]
