# Generated by Django 5.0.3 on 2025-01-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yanzheng',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
