# Generated by Django 5.0.3 on 2025-02-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/默认.jpg', null=True, upload_to='avatars/'),
        ),
    ]
